# Generated by Django 5.0.6 on 2024-07-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='email',
            new_name='correo_electronico',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='message',
            new_name='mensaje',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='reason',
        ),
        migrations.AddField(
            model_name='contacto',
            name='motivo',
            field=models.CharField(default='contacto', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(default='contacto', max_length=100),
            preserve_default=False,
        ),
    ]
